services:
  app:
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    env_file:
      - ./.env

  nginx:
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
